= Workshop: Pipelines mit Jenkins
auf dem Developer Open Space 2021
mit Johannes Thorn

Wer Software entwickelt wird schnell auch über die Themen Continous Delivery
und Continous Deployment stolpern.
Um den Wunsch danach auch zu realisieren,
muss die entsprechende Infrastruktur aufgebaut und richtig benutzt werden.
In diesem Workshop soll es um den alten Platzhirschen Jenkins
und seinen modernen Einsatz gehen.

Dabei ist es egal ob du gerade deine ersten Schritte mit Build-Servern machst
oder schon immer im Jenkins deine Jobs zusammengeklickt hast.

Im Rahmen dieses Workshops werden wir gemeinsam die Grundlagen dieser Software
kennen lernen,
erste Beispielprojekte konfigurieren
und in der Folge darauf aufbauend moderne und komplexere Setups betrachten.
Wir wollen gemeinsam die Möglichkeiten dieses Build-Servers erkunden
und uns mit dessen Stärken, Schwächen und den wichtigsten Plugins vertraut
machen.
Anhand von praktischen Beispielen und Übungen sammeln wir erste Erfahrungen
mit Jenkins Pipelines.

Gegen Ende bietet sich auch die Gelegenheit für Diskussionen
und den Vergleich mit anderen Werkzeugen.

Nimm am Workshop teil und sichere die Zukunft deiner Code-Entwicklung.

== Zielgruppe

Dieser Workshop richtet sich an Entwickler*innen die erste Erfahrungen mit
Build- und Deployment-Pipelines auf Basis von Jenkins machen wollen.

Hinweis: Es werden Grundkenntnisse zu Build-Tools und mindestens einer
Programmiersprache benötigt.
Ein GitHub-/GitLab-Account oder Vergleichbares ist für manche der Übungen
notwendig.

Die Beispiele sind auf Basis von Java und Maven vorbereitet.
Grundsätzlich sind sie jedoch übertragbar auf die meisten anderen Kombinationen
aus Sprache und Build-Tool.

== Vorläufiger Inhalt

. Begrüßung

. Jenkins Historie

. Build deployment

. Eweiterbar durch Plugin

. Legacy Jenkins Freeform jobs
.. echo

. Pipeline on the fly
.. echo

. Pipeline Grundlage

. Build-Pipeline Maven

. Jenkins Plugins übersicht

. Multipipeline PR RESULT

. Run a job in a pipeline Deploy-Pipeline Ansible? von Build aufrufen

. Themen wie Fehlerbehandlung

.  Parallelisierung