= Workshop: Pipelines mit Jenkins
auf dem Developer Open Space 2021
mit Johannes Thorn



Jenkins als führendes Werkzeug für Continuous Integration und Delivery ist bei ihnen bereits fest etabliert. Neue fachliche, technische oder organisatorische Anforderungen machen es notwendig, Ihre Prozesse in Entwicklung, Build und Delivery effizienter zu gestalten und umzusetzen. Das Konzept der Jenkins Pipeline (als Code) hilft Ihnen dabei, denn es hat Continuous Integration und Delivery maßgeblich verändert.

Mit diesem Training, und darauf aufbauenden Workshops, unterstützen wir seit mehr als fünf Jahren eine Vielzahl von Kunden unterschiedlicher Branchen, diesen Weg erfolgreich zu beschreiten. Wir bringen Ihnen die Grundlagen und best practices der Jenkins Pipeline (als Code) näher. Anhand von praktischen Beispielen und Übungen sammeln Sie erste Erfahrungen mit einer gescripteten und deklarativen Pipeline. Themen wie Fehlerbehandlung, Parallelisierung und die Verwendung von Shared Libraries runden das Training ab.




== Zielgruppe

Dieser Workshop richtet sich an Entwickler*innen die mit erste Erfahrungen mit Build- und Deployment-Pipelines auf Basis von Jenkins machen wollen.

Hinweis: Es werden Grundkenntnisse zu Containern und dem Docker-Ökosystem (z.B. Docker-Files, Docker-Compose) benötigt.


== Inhalt

. Dinge mit Jenkins
. noch mehr Ding


Um Software schnell zu entwickeln und bereitzustellen, sind Container das aktuelle Mittel der Wahl. Geht es dann aber um den skalierbaren Betrieb von einzelnen Containern oder Containerstacks, kommt man an Werkzeugen zur Orchestrierung kaum vorbei. In diesem Workshop geht es um das meistverbreitete Werkzeug Kubernetes. Erfahrt die Architektur einer Kubernetes-Umgebung und erlebt den grundlegenden Einsatz von Container mit Pods, Deployment und Services. Dabei werden auch weitergehende Konzepte zur Konfigurationsverwaltung und Metadaten genutzt. Ein Ausblick auf K3S und Updatestrategien sowie ServicesMeshs runden den spannenden Tag ab. Zielgruppe für den Workshop sind Developer die bereits ein gutes Verständnis von Container-Technologien z.B. Docker besitzen und nun in Kubernetes einsteigen möchten. Grundlegende Kenntnisse im Bereich Linux und Programmierung z. B. in C# oder Java sind empfohlen. Für die praktischen Übungen stelle ich eine Umgebung im Internet bereit. Der Zugriff erfolgt dabei mittels HTTPS und SSH. Für die Nutzung empfehle ich den plattformunabhängige Editor Microsoft Visual Studio Code mit dem Plugin Remote Development für SSH.

Nimm am Workshop teil und werde zum Steuermann (vom griechischen Kubernetes) für Container.