= Jenkins Pipelines II
:icons: font
:imagesdir: images
:hide-uri-scheme:
:source-highlighter: highlightjs
:source-language: groovy
:highlightjs-languages: groovy, yaml
:revealjs_theme: moon
:revealjs_hash:
:revealjs_width: 1440
:revealjs_height: 1200
Johannes Thorn

Wie geht es weiter?

== Deployment Pipelines

* Ein Software-Build kann in mehrere Phasen unterteilt werden.
** Build
** Test
** Deploy
** usw.
* Zur Übersicht wollen wir die Phasen auch in unserer Pipeline abbilden.

=== Wir haben nicht genügend Stages, Mylord!

ifdef::backend-revealjs[=== !]

[source.stretch]
----
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}
----

=== Eine Stage pro Deployment-Umgebung

* Häufig wollen wir verschiedene Deployment-Umgebungen unterscheiden
** Development
** Staging
** [...]
** Production
* Dafür teilen wir *das Deployment* auf mehrere Stages auf

ifdef::backend-revealjs[=== !]

[source]
----
stage('Deploy - Staging') {
    steps {
        sh './deploy.sh staging'
        sh './run-smoke-tests'
    }
}
stage('Deploy - Production') {
    steps {
        sh './deploy.sh production'
    }
}
----

=== Continuous Delivery statt Continuous Deployment

* Manchmal ist ein automatisches Deployment bis auf Produktion/Live gar nicht gewünscht.
* Manuelle Freigaben zwischen den Stages sichern das Deployment ab

ifdef::backend-revealjs[=== !]

[source.stretch]
----
pipeline {
    agent any
    stages {
        /* "Build" and "Test" stages omitted */
        stage('Deploy - Staging') {
            steps {
                sh './deploy.sh staging'
                sh './run-smoke-tests'
            }
        }
        stage('Sanity check') {
            steps {
                input "Does the staging environment look ok?"
            }
        }
        stage('Deploy - Production') {
            steps {
                sh './deploy.sh production'
            }
        }
    }
}
----

=== Milestones gegen Wartezeiten

* Standardmäßig können Pipeline-Läufe nebenläufig abgearbeitet werden.
* Das führt zu einem Problem, wenn ein neuerer Lauf einen älteren Lauf überholt.
* Milestones erzwingen eine bestimmte Ordnung beim Ablauf.
* Dadurch werden ältere Builds abgebrochen, sobald sie überholt wurden.

ifdef::backend-revealjs[=== !]

[source]
----
stage('Sanity check') {
    steps {
        input "Does the staging environment look ok?"
        milestone label: "Sanity check"
    }
}
----

=== Ablauf der Milestone Steuerung

[plantuml, target=AblaufMilestones, format=png]
....
hide footbox

[-> Run1 ++ : Start work
Run1 -> Run1 ++ : Deploy - Staging
[<- Run1 -- : waiting for input
deactivate Run1

...

[-> Run2 ++ : Start work
Run2 -> Run2 ++ : Deploy - Staging
[<- Run2 -- : waiting for input
deactivate Run2

== Milestone 1: Deployment ==

...

[-> Run2: Sanity check was successful

== Milestone 2: Sanity check ==

Run2 -> Run1 !!: abort

activate Run2
Run2 -> Run2 ++ : Deploy - Production
deactivate Run2
deactivate Run2
....

== Main Branch vs. Feature Branch?

* Bisher wird für jeden Commit die vollständige Pipeline ausgeführt.
* Bei einem Feature orientierten Branching-Modell ist das aber nicht gewünscht.
* Die Lösung sind bedingt ausgeführte Stages

=== Ausführungsbedingungen mit `when`

Zusätzliche Direktive für den Stage-Block

[source]
----
stage('Deploy - Production') {
    when {
        branch 'main'
    }
    steps {
        sh './deploy.sh production'
    }
}
----

=== Bedingungen

Die entsprechende Stage wird nur ausgeführt,

`when { branch 'main' }`:: wenn der Branch dem Pattern entspricht.
`when { buildingTag() }`:: wenn gerade ein Tag gebaut wird.
`when { tag "release-*" }`:: wenn ein Tag gebaut wird, der auf das Pattern matched.

ifdef::backend-revealjs[=== !]

`when { changelog '.*^\\[DEPEND\\] .+$' }`:: wenn der Regex auf den Logeintrag matched.
`when { changeset "**/*.js" }`:: wenn eine der geänderten Dateien auf das Pattern matched.
`when { changeRequest() }`:: wenn es sich um einen PR, MR, usw. handelt.

ifdef::backend-revealjs[=== !]

`when { environment name: 'DEPLOY_TO', value: 'prod' }`:: wenn die Umgebungsvariable gleich dem angegebenen Wert ist.
`when { equals expected: 2, actual: currentBuild.number }`:: wenn der erwartete Wert gleich dem angegebenen Wert ist.
`when { expression { return params.DEBUG_BUILD } }`:: wenn der Groovy-Ausdruck zu wahr auswertet.

=== Kombinierte Bedingungen

* Bedingungen können auch kombiniert werden.
+
----
when {
    branch 'main'
    environment name: 'DEPLOY_TO', value: 'production'
}
----
* Das entspricht einer UND-Verknüpfung aller Bedingungen.

ifdef::backend-revealjs[=== !]

Die Bedingungen können auch noch weiter verschachtelt werden.

`allOf { ... }`:: UND-Verknüpfung der Bedingungen
`anyOf { ... }`:: ODER-Verknüpfung der Bedingungen
`not { ... }`:: Negation der nachfolgenden Bedingung

== Secrets

* Jenkins bringt eine Verwaltung für verschiedene Secrets mit
** Benutzername und Passwort
** Text-Secret
** File-Secret
** SSH-Username und privater Schlüssel
** PKCS#12-Zertifikat
* Diese werden verschlüsselt auf dem Build-Server gespeichert
* und können in Pipelines verwendet werden

[source]
----
withCredentials([string(credentialsId: 'deployment-token-production', variable: 'TOKEN')]) {
    // some block
}
----

== Ihr seid wieder dran

. Im Branch `deployment01` ist Skript vorbereitet, welches das Deployment für euch regelt ;)
. Erweitert die bestehende Pipeline um ein zweistufiges Deployment mit manueller Freigabe
. Es existieren bereits zwei Secrets, die das jeweilige Deployment Token enthalten
** `deployment-token-production` sichert das Deployment nach Production ab
** `deployment-token-staging` sichert das Deployment nach Staging ab
