= Pipelines mit Jenkins
:icons: font
:imagesdir: images
:hide-uri-scheme:
:source-highlighter: highlightjs
:source-language: groovy
:highlightjs-languages: groovy, yaml
:revealjs_theme: moon
Johannes Thorn

Ich baue meine erste Pipeline mit Jenkins


== Johannes Thorn

* Softwareentwickler
* Toolsmith
* Problemlöser

*Kontakt und Fragen*

* https://twitter.com/HerrStachel[@HerrStachel] auf Twitter
* Johannes.Thorn@ecube.de per E-Mail

=== eCube GmbH

ca. 15 Mitarbeitende in Leipzig
und ca. 20 in München

* Produktdatenmanagement
** Chioro ein Produkt zum Produktdatenmanagement
** Strategieberatung
* Softwareentwicklung
** Beratung
** Umsetzung

== Jenkins Grundlagen 

image::Jenkins_logo_with_title.svg[Jenkins,50%]

[.lead]
Build great things at any scale

> The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.

=== Historie

* Jenkins ist 2011 per Fork aus dem Projekt Hudson hervorgegangen.
* Einige Zeit wurden Hudson und Jenkins parallel weiterentwickelt.
* 2016 wurde die Weiterentwicklung von Hudson zugunsten von Jenkins eingestellt.
* Die Software steht unter der MIT-Lizenz.

=== Von Continuous Build bis Continuous Deployment

* Unterstützt nahezu beliebige Integrationsszenarien
** Continous Build/Test
** Continous Integration
** Continous Delivery
** Continous Deployment
** usw.
* Erweiterbarer Automatisierungsserver
* Die Grenze ist die eigene Vorstellungskraft ;)

=== Jenkins Plugins

* Eine große Menge von vorgefertigten Plugins erleichtern die Arbeit mit verschiedenen Werkzeugen.
* Einige werden wir auch noch näher kennen lernen.
* Durch weitere Plugins kann Jenkins nahezu beliebig erweitert werden.

=== Verteilung und Orchestrierung von Aufgaben

* Jenkins ist grundsätzlich auf die verteilte Arbeit ausgelegt.
* Die Verteilung von Aufgaben über Plattformgrenzen hinweg gehört zu den Basisfeatures.
* Jenkins kann als Zentrales Verwaltungwerkzeug für automatisierte Aufträge fungieren.

== Funktionsweise von Jenkins

Eine Jenkins-Buildumgebung setzt sich typischerweise zusammen aus einem zentralen Jenkins Server und mehreren Jenkins-Buildagents.

=== Main Server

=== Buildagents

* Bekommen Aufträge vom Jenkins 

== Vorläufiger Inhalt

[.notes]
--
* Wie funktioniert Jenkins?
* Wie hat man das früher gemacht?
--

== Pipelines

Werden typischerweise in einer Datei `Jenkinsfile` im Repository-Root gepflegt.

[source%linenums]
----
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
----

== steps

* Eine Pipeline setzt sich aus mehreren `steps` zusammen.
* Jeder Step beschreibt ein Kommando, das ausgeführt wird.
* Beispiele
** `echo 'Building the project.'`
** `sh 'mvn test'`

=== Echo-Step

* Die einfachste Form des Steps.
* Der nachfolgende Inhalt wird im Build-Log ausgegeben.

----
echo 'Building the project.'
----

=== Shell-Befehle

* Kaum komplizierter als ein `echo`.
* Das nachfolgende Kommando wird innerhalb einer Shell ausgeführt.
* Auf Unix-artigen wird `sh` verwendet, um einen Befehl  in einer Shell auszuführen.
* Unter Windows wird `bat` verwendet.

----
sh 'mvn test'
sh 'npm test'
sh 'COMMAND'
----

== stage

== stages

== agent



== Pipeline Jobs

=== Multibranch Pipeline

* Eine Multibranch Pipeline wird ausgehend von einem VCS-Repository definiert.
* Jeder Branch in diesem Repository erzeugt einen eigenen Job innerhalb des übergeordneten Jobs.

=== Pipeline

=== Organization

== Anhang

Hier beginnt der Anhang, den schauen wir uns nur an, wenn uns langweilig ist :D

== Jenkins via Docker 

Deploye einen Jenkins Build-Server via Docker

----
docker run -p 8080:8080 -p 50000:50000 \
  -v jenkins_home:/var/jenkins_home \
  jenkins/jenkins:lts-jdk11
----

Die Weboberfläche ist jetzt unter http://localhost:8080 erreichbar

Details siehe https://github.com/jenkinsci/docker/

== Slide Two

A Great Story

ifdef::backend-revealjs[=== !]

with a good ending

WARNING: hello

INFO: good gid


== Pipeline Code

[source]
----
def foo = "Hello world"

pipeline Hallo {
  agent {
    label "venlo"
  }
  
  triggers {
    pollSCM ""
    if (foo) {
      echo "do something"
    }
  }
  
  options {
    timestamps()
    ansiColor("xterm")
  }
  
  steps {
    echo "Hallo Welt"
  }
}
----
